config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#redirect'
  get '/ruby', to: 'application#ruby'
  get '/oauth2callback', to: 'application#callback', as: 'callback'
  get '/redirect', to: 'application#redirect', as: 'redirect'

  get '/facebook', to:'application#implementation_fbapi', as: 'implementation_fbapi'
  get '/get_value/:id', to: 'application#get_value', as:'get_value'
  get '/analytics/account/:id/time/:time', to: 'application#view', as:'view_analytics'
  get '/report/:id/time/:time', to: 'application#report', as: 'report'
  get '/print_excel/:id/time/:time', to: 'application#print_excel', as: 'print_excel'

  post '/analytics', to: 'application#analytics', as: 'analytics'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :ensure_credentials
  # before_action :set_analytics, only: [:ruby]
  # after_action :after

  require 'googleauth'
  require 'google/apis/analytics_v3'

  require 'koala'

## facebook

  def implementation_fbapi
    FacebookAds.configure do |config|
      config.access_token = 'EAAS9Tripd30BAINdDLZBstOM1GwbmvANzlGfgFY6KecSQixmCi9GkfYTyywF1vtvGEB5YBxV6XMpq7TUBjyIOGkphm0SdVsq6CC75F3oP1ZBzyVVEhCdIgQpy1sU66xjHO59Ng187TxhGq9f0lEcMOZCsMeELMdknZB5fHD6xgZDZD'
      config.app_secret = 'f81516205be0682015e36e931f387c08'
    end
    @names = Array.new
    act_accounts = FacebookAds.me.adaccounts.to_a.map { |x| x['id']}.take(5)
    act_accounts.each do |account|
      temp_name = FacebookAds::AdAccount.get(account)
      @names << [temp_name.name, account]
    end
  end

  def get_value
    @value =  Array.new
    begin
      account_id =  params[:id]
      account = FacebookAds::AdAccount.get(account_id)
      account.campaigns.each  do |campaign|
        temp_value = get_info(campaign)
        if !temp_value.nil?
          @value << temp_value
        end
      end
    rescue Exception => e
      puts e
      return @value
    end
    # this is temporary
    # print_excel_campaigns(@value, account.name)
  end

  def get_info campaign
    begin
      temp_objective = campaign.objective
      if temp_objective == 'PAGE_LIKES' || temp_objective == 'CONVERSIONS' || temp_objective == 'LINK_CLICKS'
        info = cpc_facturation(campaign)
      elsif temp_objective == 'REACH' || temp_objective == 'POST_ENGAGEMENT'
        info = cpm_facturation(campaign)
      end
      return info
    rescue Exception => e
      puts e
      return nil
    end
  end

  def cpm_facturation campaign
    campaign = campaign
    begin
     if !campaign.insights[0].nil?
        value = {nombre: campaign.name, alcance: campaign.insights(fields: 'reach').map(&:reach), cpm: campaign.insights(fields: 'cpm').map(&:cpm),
          impresiones: campaign.insights(fields: 'impressions').map(&:impressions), total_cost: campaign.insights(fields: 'total_action_value').map(&:total_action_value),
          ctr: campaign.insights(fields: 'ctr').map(&:ctr)}
      return value
     end
    rescue Exception => e
      puts  e
      return value
    end
  end

  def cpc_facturation campaign
    campaign = campaign
    begin
      if !campaign.insights[0].nil?
        value =  {nombre: campaign.name, alcance: campaign.insights(fields: 'reach').map(&:reach), cpc: campaign.insights(fields: 'cpc').map(&:cpc),
          impresiones: campaign.insights(fields: 'impressions').map(&:impressions), total_cost: campaign.insights(fields: 'total_action_value').map(&:total_action_value),
          ctr: campaign.insights(fields: 'ctr').map(&:ctr)}
        return value
      end
    rescue Exception => e
      puts  e
      return value
    end
  end

  def cpl_facturation campaign
    campaign = campaign
    begin
      if !campaign.insights[0].nil?
        value = {nombre: campaign.name, alcance: campaign.insights(fields: 'reach').map(&:reach), cpl: campaign.insights(fields: 'cpl').map(&:cpl),
          impresiones: campaign.insights(fields: 'impressions').map(&:impressions), total_cost: campaign.insights(fields: 'total_action_value').map(&:total_action_value),
          ctr: campaign.insights(fields: 'ctr').map(&:ctr)}
        return value
      end
    rescue Exception => e
      puts  e
      return value
    end
  end


  def cpv_facturation campaign
    campaign = campaign
    begin
      if !campaign.insights[0].nil?
        value = {nombre: campaign.name, alcance: campaign.insights(fields: 'reach').map(&:reach), cpv: campaign.insights(fields: 'cpv').map(&:cpv),
                      impresiones: campaign.insights(fields: 'impressions').map(&:impressions), total_cost: campaign.insights(fields: 'total_action_value').map(&:total_action_value),
                      ctr: campaign.insights(fields: 'ctr').map(&:ctr)}
        return value
      end
    rescue Exception => e
      puts  e
      return value
    end
  end

  def cpa_facturation campaign
    campaign = campaign
    begin
      if !campaign.insights[0].nil?
        value = {nombre: campaign.name, alcance: campaign.insights(fields: 'reach').map(&:reach), cpa: campaign.insights(fields: 'cpa').map(&:cpa),
                      impresiones: campaign.insights(fields: 'impressions').map(&:impressions), total_cost: campaign.insights(fields: 'total_action_value').map(&:total_action_value),
                      ctr: campaign.insights(fields: 'ctr').map(&:ctr)}
        return value
      end
    rescue Exception => e
      puts  e
      return value
    end
  end

## Analytics

  # def ruby
  #   @events = @ga.list_events('primary', options: { authorization: user_credentials })
  # end

  def redirect
    client = Signet::OAuth2::Client.new(client_options)

    redirect_to client.authorization_uri.to_s
  end

  def callback
    client = Signet::OAuth2::Client.new(client_options)
    client.code = params[:code]

    response = client.fetch_access_token!
    logger.info(response)
    session[:authorization] = response

    redirect_to '/ruby'
  end

  def ruby
    service = analytics_service
    @account_summaries = service.list_account_summaries
  rescue Google::Apis::AuthorizationError
    @autherror = true
  end

  def analytics
    time = params[:time]
    account = params[:account]
    action = params[:action]
    respond_to do |format|
      case action
        when "Ver información"
          format.html {redirect_to view_analytics_path(account, time)}
        when "Descargar PDF"
          format.html {redirect_to report_path(account, time, :format => :pdf)}
      end
    end
  end

  def view
    @account = params[:id]
    @time = params[:time]
    @ga_convertions = get_convertions.rows
    @ga_convertions = sort_descending(@ga_convertions)
    @ga_cities = get_cities.rows
    @ga_cities = sort_descending(@ga_cities)
    @ga_gender = get_gender.rows
    @ga_gender = sort_descending(@ga_gender)
    @ga_age = get_age.rows
    @ga_age = sort_descending(@ga_age)
  end



  def print_excel
    account = params[:id]
    ga_convertions = sort_descending(get_convertions.rows)
    ga_cities = sort_descending(get_cities.rows)
    ga_gender = sort_descending(get_gender.rows)
    ga_age = sort_descending(get_age.rows)
    excel = Axlsx::Package.new
    name_document = "informe.xlsx"
    excel.workbook.styles do |style|
      wrap_text = style.add_style :alignment => {:horizontal => :left, :vertical => :center, :wrap_text => true}
      excel.workbook.add_worksheet(name: "Conversiones") do |sheet|
        sheet.add_row ["Conversiones", ""]
        if !ga_convertions.nil?
          ga_convertions.each do |conversion|
            sheet.add_row [conversion[0], conversion[1]], style: wrap_text
          end
          sheet.merge_cells "A1:B1"
        end
      end
      excel.workbook.add_worksheet(name: "Ciudad") do |sheet|
        sheet.add_row ["Ciudad", ""]
        if !ga_cities.nil?
          ga_cities.each do |ciudad|
            sheet.add_row [ciudad[0], ciudad[1]], style: wrap_text
          end
          sheet.merge_cells "A1:B1"
        end
      end
      excel.workbook.add_worksheet(name: "Genero") do |sheet|
        sheet.add_row ["Genero", ""]
        if !ga_gender.nil?
          ga_gender.each do |genero|
            sheet.add_row [genero[0], genero[1]], style: wrap_text
          end
          sheet.merge_cells "A1:B1"
        end
      end
      excel.workbook.add_worksheet(name: "Edad") do |sheet|
        sheet.add_row ["Edad", ""]
        if !ga_age.nil?
          ga_age.each do |edad|
            sheet.add_row [edad[0], edad[1]], style: wrap_text
          end
          sheet.merge_cells "A1:B1"
        end
      end
      excel.use_shared_strings = true
      send_data excel.to_stream.read, type: "application/xlsx", filename: name_document
    end
    return
  end

  def get_convertions
    service = analytics_service
    profile_id = 'ga:'+params[:id]
    time = params[:time]
    @analytics = service.get_ga_data(profile_id,time,'today','ga:goalCompletionsAll',{dimensions: "ga:sourceMedium"})
  rescue Google::Apis::AuthorizationError
    redirect
  end

  def get_cities
    service = analytics_service
    profile_id = 'ga:'+params[:id]
    time = params[:time]
    @analytics = service.get_ga_data(profile_id,time,'today','ga:sessions',{dimensions: "ga:city"})
  rescue Google::Apis::AuthorizationError
    redirect
  end

  def get_gender
    service = analytics_service
    profile_id = 'ga:'+params[:id]
    time = params[:time]
    @analytics = service.get_ga_data(profile_id,time,'today','ga:sessions',{dimensions: "ga:userGender"})
  rescue Google::Apis::AuthorizationError
    redirect
  end

  def get_age
    service = analytics_service
    profile_id = 'ga:'+params[:id]
    time = params[:time]
    @analytics = service.get_ga_data(profile_id,time,'today','ga:sessions',{dimensions: "ga:userAgeBracket"})
  rescue Google::Apis::AuthorizationError
    redirect
  end

  def report
    @ga_convertions = get_convertions.rows
    @ga_convertions = sort_descending(@ga_convertions)
    @ga_cities = get_cities.rows
    @ga_cities = sort_descending(@ga_cities)
    @ga_gender = get_gender.rows
    @ga_gender = sort_descending(@ga_gender)
    @ga_age = get_age.rows
    @ga_age = sort_descending(@ga_age)
    date = DateTime.now
    @start_date = get_start_date
    @end_date = date.strftime("%d/%m/%Y")
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "reporte"
      end
    end
  end

  private

  def client_options
    if Rails.env.production?
      redirect_uri = 'https://habla-reports.herokuapp.com/oauth2callback'
    else
      redirect_uri = 'http://localhost:3000/oauth2callback'
    end
    {

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/get_value.html.erb
<section>
  <article>
    <div class="container">
      <div class="row">
        <table class="table">
          <thead>
            <tr>
              <th>Nombre Campaña</th>
              <th>Alcance</th>
              <th>Impresiones</th>
              <th>CPC</th>
              <th>CPL</th>
              <th>CPM</th>
              <th>CPA</th>
              <th>CPV</th>
              <th>CTR</th>
              <th>Costo Total</th>
            </tr>
          </thead>
          <tbody>
            <% @value.each do |value| %>
            <tr>
              <td> <%= value[:nombre] %> </td>
              <td> <%= value[:alcance][0] %></td>
              <td> <%= value[:impresiones][0] %></td>
              <% if !value[:cpc].nil? %>
                <td> <%= value[:cpc][0] %></td>
              <% else %>
                <td> </td>
              <% end %>
              <% if !value[:cpl].nil? %>
                <td> <%= value[:cpl][0] %></td>
              <% else %>
                <td> </td>
              <% end %>
              <% if !value[:cpm].nil? %>
                <td> <%= value[:cpm][0] %></td>
              <% else %>
                <td> </td>
              <% end %>
              <% if !value[:cpa].nil? %>
                <td> <%= value[:cpa][0] %></td>
              <% else %>
                <td> </td>
              <% end %>
              <% if !value[:cpv].nil? %>
                <td> <%= value[:cpv][0] %></td>
              <% else %>
                <td> </td>
              <% end %>
              <td> <%= value[:ctr][0] %></td>
              <td> <%= value[:total_cost][0] %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </article>
</section>

app/views/application/implementation_fbapi.html.erb
<style>
  body {
    margin: 0;
  }

  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 25%;
    background-color: #f1f1f1;
    position: fixed;
    height: 100%;
    overflow: auto;
  }

  li a {
    display: block;
    color: #000;
    padding: 8px 16px;
    text-decoration: none;
  }

  li a.active {
    background-color: #4CAF50;
    color: white;
  }

  li a:hover:not(.active) {
    background-color: #555;
    color: white;
  }
  </style>
</style>

<section>
  <article>
    <div>
      <ul>
        <li><a class="active" href="#home">Home</a></li>
        <% @names.each do |user| %>
          <li><a href="/get_value/<%= user[1] %>"> <%= user[0] %> </a></li>
        <% end %>
      </ul>
    </div>
    <div id="container" style="height: 400px; min-width: 310px"></div>

  </article>
</section>

app/views/application/index.html.erb
<h1>Hello Analytics Reporting API V4</h1>

<p>
  <!-- The Sign-in button. This will run `queryReports()` on success. -->
  <div class="g-signin2" data-onsuccess="queryReports"></div>
</p>

<!-- The API response will be printed here. -->
<textarea cols="80" rows="20" id="query-output"></textarea>

<script>
  // Replace with your view ID.
  var VIEW_ID = '129076505'; //Centros logisticos formulario

  // Query the API and print the results to the page.
  function queryReports() {
    gapi.client.request({
      path: '/v4/reports:batchGet',
      root: 'https://analyticsreporting.googleapis.com/',
      method: 'POST',
      /* cities */
      /*body: {
        reportRequests: [
          {
            viewId: VIEW_ID,
            dateRanges: [
              {
                startDate: '7daysAgo',
                endDate: 'today'
              }
            ],
            metrics: [
              {
                expression: 'ga:sessions'
              }
            ],
            dimensions: [
              {name: "ga:city"}
            ]
          }
        ]
      }*/
      /* Conversion goals */
      /*body: {
        reportRequests: [
          {
            viewId: VIEW_ID,
            dateRanges: [
              {
                startDate: '7daysAgo',
                endDate: 'today'
              }
            ],
            metrics: [
              {
                expression: 'ga:goalCompletionsAll'
              }
            ],
            dimensions: [
              {name: "ga:sourceMedium"}
            ]
          }
        ]
      }*/
      /* user ages */
      /*body: {
        reportRequests: [
          {
            viewId: VIEW_ID,
            dateRanges: [
              {
                startDate: '7daysAgo',
                endDate: 'today'
              }
            ],
            metrics: [
              {
                expression: 'ga:users'
              }
            ],
            dimensions: [
              {name: "ga:userAgeBracket"}
            ]
          }
        ]
      }*/
      /* users's gender */
      body: {
        reportRequests: [
          {
            viewId: VIEW_ID,
            dateRanges: [
              {
                startDate: '7daysAgo',
                endDate: 'today'
              }
            ],
            metrics: [
              {
                expression: 'ga:users'
              }
            ],
            dimensions: [
              {name: "ga:userGender"}
            ]
          }
        ]
      }

    }).then(displayResults, console.error.bind(console));
  }

  function displayResults(response) {
    var formattedJson = JSON.stringify(response.result, null, 2);
    document.getElementById('query-output').value = formattedJson;
  }
</script>

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId            : '973735409321721',
      autoLogAppEvents : true,
      xfbml            : true,
      version          : 'v2.11'
    });
    FB.AppEvents.logPageView();
  };

  FB.api('/me/adaccounts');

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>


<!-- Load the JavaScript API client and Sign-in library. -->
<script src="https://apis.google.com/js/client:platform.js"></script>

app/views/application/ruby.html.erb
<% unless @autherror %>
<h1>Cuentas de analytics</h1>
<div class="btn-group-vertical" role="group" aria-label="Button group with nested dropdown">
    <% @account_summaries.items.each do |result| %>
    <div class="btn-group" role="group">
        <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= result.name %>
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1"> 
            <% result.web_properties.each do |propertie| %>
                <%= link_to ( propertie.name+' - '+propertie.website_url+' - '+propertie.profiles[0].id ), view_analytics_path(propertie.profiles[0].id, '30daysAgo'), class: 'dropdown-item' %>
            <% end %>
        </div>
    </div>
    <% end %>
  </div>
  <% else %>
  hay un error de permisos
  <%= link_to  "Login with google", redirect_path %>
  <% end %>

<div class="container">
    <%= form_tag analytics_path do |f| %>
        <div class="form-group">
            <%= label_tag :account, "Cuenta" %>
            <%= select_tag :account, options_for_select(@account_summaries.items.collect {|c| [ c.web_properties.first.name.to_s, c.web_properties.first.profiles[0].id.to_s] }), class: 'form-control' %>
        </div>
        <div class="form-group">
           <%= label_tag :time, "Antigüedad de los datos" %> 
           <%= select_tag :tiem, options_for_select(["30daysAgo", "14daysAgo", "7daysAgo"]), class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= label_tag :action, "¿Qué desea hacer?" %> 
            <%= select_tag :tiem, options_for_select(["Ver información", "Descargar PDF", "Descargar xlsx"]), class: 'form-control' %>
        </div>
        <div class="actions">
            <input type="submit" value="listo!" class="btn btn-primary">
        </div>
    <% end %>
</div>

<!-- <h1>Cuentas de Analytics</h1>
<table>
    <%# @account_summaries.items.each do |result| %>
    <tr>
            <td>
                <%#= result.name %>
                <ul>
                    <%# result.web_properties.each do |propertie| %>
                    <li><%#= propertie.name %> - <%#= propertie.website_url %></li>
                    <%# end %>
                </ul>
            </td>
    </tr>
    <%# end %>
</table> -->

<table>
<!-- <%# @analytics.rows.each do |result| %>
<tr>
    <%# result.each do |column| %>
        <td>
            <%#= column %>
        </td>
    <%# end %>
</tr>
<%# end %> -->
</table>

app/views/application/view.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 text-right">
            <div class="btn-group" role="group" aria-label="Select time">
                <%= link_to  "hace 7 dias", view_analytics_path(@account, '7daysAgo'), class: 'btn btn-secondary' %>
                <%= link_to  "hace 2 semanas", view_analytics_path(@account, '14daysAgo'), class: 'btn btn-secondary' %>
                <%= link_to  "hace 30 dias", view_analytics_path(@account, '30daysAgo'), class: 'btn btn-secondary' %>
            </div>
            <%= link_to  "descargar reporte", report_path(@account, @time, :format => :pdf) %>
            <%= link_to  "descargar reporte xlsx", print_excel_path(@account, @time, :format => :xlsx) %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h1>Conversiones</h1>
            <% unless @ga_convertions.nil? %>
            <table class="table table-striped">
                <% @ga_convertions.first(10).each do |result| %>
                <tr>
                    <% result.each do |column| %>
                        <td>
                            <%= column %>
                        </td>
                    <% end %>
                </tr>
                <% end %>
            </table>
            <% else %>
                Vaya, al parecer no hay datos aqui, puede que tengas deshablitada esta opción en tu cuenta de Analytics
            <% end %>
        </div>
        <div class="col-md-3">
            <h1>Ciudades</h1>
            <% unless @ga_cities.nil? %>
            <table class="table table-striped">
                <% @ga_cities.first(10).each do |result| %>
                <tr>
                    <% result.each do |column| %>
                        <td>
                            <%= column %>
                        </td>
                    <% end %>
                </tr>
                <% end %>
            </table>
            <% else %>
                Vaya, al parecer no hay datos aqui, puede que tengas deshablitada esta opción en tu cuenta de Analytics
            <% end %>
        </div>
        <div class="col-md-3">
            <h1>Género</h1>
            <% unless @ga_gender.nil? %>
            <table class="table table-striped">
                <% @ga_gender.first(10).each do |result| %>
                <tr>
                    <% result.each do |column| %>
                        <td>
                            <%= column %>
                        </td>
                    <% end %>
                </tr>
                <% end %>
            </table>
            <div id="pie" style="width:100%; height:400px;"></div>
            <% else %>
                Vaya, al parecer no hay datos aqui, puede que tengas deshablitada esta opción en tu cuenta de Analytics
            <% end %>
        </div>
        <div class="col-md-3">
            <h1>Edades</h1>
            <% unless @ga_age.nil? %>
            <table class="table table-striped">
                <% @ga_age.first(10).each do |result| %>
                <tr>
                    <% result.each do |column| %>
                        <td>
                            <%= column %>
                        </td>
                    <% end %>
                </tr>
                <% end %>
            </table>
            <% else %>
                Vaya, al parecer no hay datos aqui, puede que tengas deshablitada esta opción en tu cuenta de Analytics
            <% end %>
        </div>
    </div>
</div>
<div id="conversions" style="width:100%; height:400px;"></div>
<div id="container" style="width: 100%; height:400px;"></div>

<script>
    $(function () { 
        var myChart = Highcharts.chart('container', {
            chart: {
                type: 'bar'
            },
            title: {
                text: 'Sesiones por ciudad'
            },
            xAxis: {
                categories: [
                    <% @ga_cities.first(10).each do |result| %>
                        "<%= result.first %>" ,
                    <% end %>
                ]
            },
            yAxis: {
                title: {
                    text: 'Sesiones'
                }
            },
            series: [{
                name: 'Sesiones',
                data: [
                    <% @ga_cities.first(10).each do |result| %>
                        <%= result[1] %> ,
                    <% end %>
                ]
            }]
        });
    });

    $(function () {
       <% if @ga_gender.first[0] == 'male'
            index_male = 0 
           index_female = 1
         else
           index_male = 1
           index_female = 0
         end %>
        var myChart = Highcharts.chart('pie', {
            title: {
                text: 'Gender'
            },
            series: [{
                type: 'pie',
                name: 'personas',
                data: [{
                    name: 'Hombres',
                    y: <%= @ga_gender[index_male][1] %> ,
                    color: Highcharts.getOptions().colors[0] // Jane's color
                }, {
                    name: 'Mujeres',
                    y: <%= @ga_gender[index_female][1] %> ,
                    color: Highcharts.getOptions().colors[2] // John's color
                }],
                showInLegend: false,
                dataLabels: {
                    enabled: true
                }
            }]
        });
    });

    $(function () {
         var myChart = Highcharts.chart('conversions', {
             title: {
                 text: 'Conversiones'
             },
             series: [{
                 type: 'pie',
                 name: 'Conversiones',
                 data: [
                 <% @ga_convertions.each_with_index do |result, index| %>
                 {
                     name: "<%= result[0] %>",
                     y: <%= result[1] %> ,
                     color: Highcharts.getOptions().colors[<%= index %>] // Jane's color
                 }
                 <% break if result[1] == "0"  %> 
                 ,
                <% end %> ],
                 showInLegend: true,
                 dataLabels: {
                     enabled: false
                 }
             }]
         });
     });
     </script>